# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-14 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(max_length=9)),
                ('scores', models.IntegerField(max_length=8)),
            ],
        ),
    ]
