# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-14 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScoreSort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscores',
            name='scores',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userscores',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
