# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-05-14 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScoreSort', '0002_auto_20200514_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscores',
            name='uid',
            field=models.CharField(max_length=32),
        ),
    ]
